PATH=$(CMTROOT)/$(CMTBIN):/nfs/farm/g/glast/u05/gcc-2.95.3/bin:/u/ek/xchen/bin.linux:/u/ek/xchen/bin:/usr/local/bin:/usr/afsws/bin:/usr/afsws/etc:/bin:/usr/bin:/usr/etc:/usr/bin/X11:.:/afs/slac.stanford.edu/package/cernlib/rs_aix41/cern/98/bin:/afs/slac.stanford.edu/u/ek/dsl/bin:/space1/ARGOS/USA/bin:/space1/ARGOS/USA/scripts:/usr/oracle/bin:/usr/oracle/ctx/lib:/afs/slac.stanford.edu/g/glast/applications/install/@sys/usr/bin:/afs/slac.stanford.edu/g/glast/ground/releases:/afs/slac.stanford.edu/g/glast/ground/scripts:/afs/slac.stanford.edu/g/glast/ground/scripts/ReleaseManager::$(ROOTSYS)/bin
CLASSPATH=/usr/oracle/jdbc/lib/classes111.zip:/usr/oracle/sqlj/lib/translator.zip:/usr/oracle/rdbms/jlib/aqapi11.jar:/usr/oracle/sqlj/demo::$(CMTROOT)/java
debug_option=-g
cdebugflags=$(debug_option)
pp_cflags=-Di586
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags)
ppcmd=-I
cpp=g++-2.95.3
cppdebugflags=$(debug_option)
cppflags=-pipe -ansi -W -Wall  -fPIC -shared -D_GNU_SOURCE -Dlinux -Dunix 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppoptions) $(cppflags) $(pp_cppflags)
cpplinkflags=-Wl,-Bdynamic $(makeLinkMap) $(linkdebug)
cpplink=$(cpp)   $(cpplinkflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar r
ranlib=ranlib
make_shlib=$(CMTROOT)/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++-2.95.3
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
build_library_links=$(cmtexe) build library_links -quiet -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -quiet -tag=$(tags)
cmtexe=$(CMTROOT)/$(CMTBIN)/cmt.exe
tags=$(CMTEXTRATAGS)
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -quiet -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
implied_library_prefix=-l
SHELL=/bin/sh
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
lock_command=chmod -R a-w ../*
unlock_command=chmod -R g+w ../*
MAKEFLAGS= --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=cp 
uninstall_command=/bin/rm -f 
mkdir=mkdir
BINDIR=rh72_gcc2953
cppoptions=$(cppdebugflags_s)
cppdebugflags_s=-g
cppoptimized_s=-O2
cppprofiled_s=-pg
linkdebug=-g 
makeLinkMap=-Wl,-Map,Linux.map
componentshr_linkopts=-fPIC  -ldl 
libraryshr_linkopts=-fPIC -ldl 
GlastMain=$(GLASTPOLICYROOT)/src/GlastMain.cxx
TestGlastMain=$(GLASTPOLICYROOT)/src/TestGlastMain.cxx
mcRootData_linkopts=-L$(mcRootDataDir) -lmcRootData 
LD_LIBRARY_PATH=:/nfs/farm/g/glast/u06/chen/glast_mc/GlastRelease_v3r3p2/mcRootData/v2r11p4/$(BINDIR):/nfs/farm/g/glast/u06/chen/glast_mc/GlastRelease_v3r3p2/digiRootData/v4r1p2/$(BINDIR):/nfs/farm/g/glast/u06/chen/glast_mc/GlastRelease_v3r3p2/reconRootData/v4r3p0/$(BINDIR):/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/ROOT/v3.04.02/root/bin:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/ROOT/v3.04.02/root/lib
digiRootData_linkopts=-L$(digiRootDataDir) -ldigiRootData 
reconRootData_linkopts=-L$(reconRootDataDir) -lreconRootData 
PLATARCHdef=rh61_gcc2952
PLATARCH=rh72_gcc2953
EXTPACK_DIR=$(GLAST_EXT)
ROOT_DIR=$(EXTPACK_DIR)/ROOT
PYTHON_DIR=$(EXTPACK_DIR)/Python
XERCES_DIR=$(EXTPACK_DIR)/Xerces-C
BOOST_DIR=$(EXTPACK_DIR)/Boost
AIDA_DIR=$(EXTPACK_DIR)/AIDA
CLHEP_DIR=$(EXTPACK_DIR)/CLHEP
HTL_DIR=$(EXTPACK_DIR)/HTL
NAGC_DIR=$(EXTPACK_DIR)/Nag_C
GSL_DIR=$(EXTPACK_DIR)/GSL
GEANT4_DIR=$(EXTPACK_DIR)/geant4
MYSQL_DIR=$(EXTPACK_DIR)/MYSQL
ROOT_native_version=v3.04.02
ROOT_PATH=$(ROOT_DIR)/$(ROOT_native_version)/root
ROOTSYS=/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/ROOT/v3.04.02/root
dict=../dict/
rootcint=rootcint
ROOT_libs=-L$(ROOT_PATH)/lib -lCore -lCint -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lpthread -lm -ldl -rdynamic 
ROOT_linkopts=$(ROOT_libs)
ROOT_cppflagsEx=$(ppcmd) "$(ROOT_PATH)/include" -DUSE_ROOT
includes=-I $(CALIBGENCALROOT)  $(use_includes)
source=*.cxx
calibgencal_linkopts=$(ROOT_linkopts) $(mcRootData_linkopts) $(digiRootData_linkopts) $(reconRootData_linkopts)
GlastPolicyDir=$(GLASTPOLICYROOT)/$(BINDIR)
mcRootDataDir=$(MCROOTDATAROOT)/$(BINDIR)
digiRootDataDir=$(DIGIROOTDATAROOT)/$(BINDIR)
reconRootDataDir=$(RECONROOTDATAROOT)/$(BINDIR)
RootPolicyDir=$(ROOTPOLICYROOT)/$(BINDIR)
calibGenCALDir=$(CALIBGENCALROOT)/$(BINDIR)
tag=rh72_gcc2953
calibGenCAL_tag=$(tag)
CALIBGENCALROOT=/a/sulky07/g.glast.u06/chen/glast_mc/GlastRelease_v3r3p2/calibGenCAL/v0
PACKAGE_ROOT=$(CALIBGENCALROOT)
calibGenCAL_root=../../../calibGenCAL/v0
CALIBGENCALVERSION=v0
srcdir=../src
bin=../$(calibGenCAL_tag)/
javabin=../classes/
mgrdir=cmt
version=v0
package=calibGenCAL
reconRootData_tag=$(tag)
RECONROOTDATAROOT=/nfs/farm/g/glast/u06/chen/glast_mc/GlastRelease_v3r3p2/reconRootData/v4r3p0
reconRootData_root=/nfs/farm/g/glast/u06/chen/glast_mc/GlastRelease_v3r3p2/reconRootData/v4r3p0
RECONROOTDATAVERSION=v4r3p0
digiRootData_tag=$(tag)
DIGIROOTDATAROOT=/nfs/farm/g/glast/u06/chen/glast_mc/GlastRelease_v3r3p2/digiRootData/v4r1p2
digiRootData_root=/nfs/farm/g/glast/u06/chen/glast_mc/GlastRelease_v3r3p2/digiRootData/v4r1p2
DIGIROOTDATAVERSION=v4r1p2
mcRootData_tag=$(tag)
MCROOTDATAROOT=/nfs/farm/g/glast/u06/chen/glast_mc/GlastRelease_v3r3p2/mcRootData/v2r11p4
mcRootData_root=/nfs/farm/g/glast/u06/chen/glast_mc/GlastRelease_v3r3p2/mcRootData/v2r11p4
MCROOTDATAVERSION=v2r11p4
RootPolicy_tag=$(tag)
ROOTPOLICYROOT=/nfs/farm/g/glast/u06/chen/glast_mc/GlastRelease_v3r3p2/RootPolicy/v2r1p2
RootPolicy_root=/nfs/farm/g/glast/u06/chen/glast_mc/GlastRelease_v3r3p2/RootPolicy/v2r1p2
ROOTPOLICYVERSION=v2r1p2
GlastPolicy_tag=$(tag)
GLASTPOLICYROOT=/nfs/farm/g/glast/u06/chen/glast_mc/GlastRelease_v3r3p2/GlastPolicy/v5r3
GlastPolicy_root=/nfs/farm/g/glast/u06/chen/glast_mc/GlastRelease_v3r3p2/GlastPolicy/v5r3
GLASTPOLICYVERSION=v5r3
ROOT_tag=$(tag)
ROOTROOT=/nfs/farm/g/glast/u06/chen/glast_mc/GlastRelease_v3r3p2/IExternal/ROOT/v2r30402p0
ROOT_root=/nfs/farm/g/glast/u06/chen/glast_mc/GlastRelease_v3r3p2/IExternal/ROOT/v2r30402p0
ROOTVERSION=v2r30402p0
ExternalLibs_tag=$(tag)
EXTERNALLIBSROOT=/nfs/farm/g/glast/u06/chen/glast_mc/GlastRelease_v3r3p2/IExternal/ExternalLibs/v4r0p3
ExternalLibs_root=/nfs/farm/g/glast/u06/chen/glast_mc/GlastRelease_v3r3p2/IExternal/ExternalLibs/v4r0p3
EXTERNALLIBSVERSION=v4r0p3
use_requirements=requirements $(CMTROOT)/mgr/requirements $(RECONROOTDATAROOT)/cmt/requirements $(DIGIROOTDATAROOT)/cmt/requirements $(MCROOTDATAROOT)/cmt/requirements $(ROOTPOLICYROOT)/cmt/requirements $(GLASTPOLICYROOT)/cmt/requirements $(ROOTROOT)/cmt/requirements $(EXTERNALLIBSROOT)/cmt/requirements 
use_includes= $(ppcmd)"$(RECONROOTDATAROOT)" $(ppcmd)"$(DIGIROOTDATAROOT)" $(ppcmd)"$(MCROOTDATAROOT)" $(ppcmd)"$(GLASTPOLICYROOT)" $(ppcmd)"$(ROOT_PATH)/include" 
use_fincludes= $(use_includes)
use_stamps= $(calibGenCAL_stamps)  $(reconRootData_stamps)  $(digiRootData_stamps)  $(mcRootData_stamps)  $(RootPolicy_stamps)  $(GlastPolicy_stamps)  $(ROOT_stamps)  $(ExternalLibs_stamps) 
use_cflags=  $(calibGenCAL_cflags)  $(reconRootData_cflags)  $(digiRootData_cflags)  $(mcRootData_cflags)  $(RootPolicy_cflags)  $(GlastPolicy_cflags)  $(ROOT_cflags)  $(ExternalLibs_cflags) 
use_pp_cflags=  $(calibGenCAL_pp_cflags)  $(reconRootData_pp_cflags)  $(digiRootData_pp_cflags)  $(mcRootData_pp_cflags)  $(RootPolicy_pp_cflags)  $(GlastPolicy_pp_cflags)  $(ROOT_pp_cflags)  $(ExternalLibs_pp_cflags) 
use_cppflags=  $(calibGenCAL_cppflags)  $(reconRootData_cppflags)  $(digiRootData_cppflags)  $(mcRootData_cppflags)  $(RootPolicy_cppflags)  $(GlastPolicy_cppflags)  $(ROOT_cppflags)  $(ExternalLibs_cppflags) 
use_pp_cppflags=  $(calibGenCAL_pp_cppflags)  $(reconRootData_pp_cppflags)  $(digiRootData_pp_cppflags)  $(mcRootData_pp_cppflags)  $(RootPolicy_pp_cppflags)  $(GlastPolicy_pp_cppflags)  $(ROOT_pp_cppflags)  $(ExternalLibs_pp_cppflags) 
use_fflags=  $(calibGenCAL_fflags)  $(reconRootData_fflags)  $(digiRootData_fflags)  $(mcRootData_fflags)  $(RootPolicy_fflags)  $(GlastPolicy_fflags)  $(ROOT_fflags)  $(ExternalLibs_fflags) 
use_pp_fflags=  $(calibGenCAL_pp_fflags)  $(reconRootData_pp_fflags)  $(digiRootData_pp_fflags)  $(mcRootData_pp_fflags)  $(RootPolicy_pp_fflags)  $(GlastPolicy_pp_fflags)  $(ROOT_pp_fflags)  $(ExternalLibs_pp_fflags) 
use_linkopts=  $(calibGenCAL_linkopts)  $(reconRootData_linkopts)  $(digiRootData_linkopts)  $(mcRootData_linkopts)  $(RootPolicy_linkopts)  $(GlastPolicy_linkopts)  $(ROOT_linkopts)  $(ExternalLibs_linkopts) 
use_libraries= $(reconRootData_libraries)  $(digiRootData_libraries)  $(mcRootData_libraries)  $(RootPolicy_libraries)  $(GlastPolicy_libraries)  $(ROOT_libraries)  $(ExternalLibs_libraries) 
fincludes= $(includes)
runMuonCalib_use_linkopts=  $(calibGenCAL_linkopts)  $(reconRootData_linkopts)  $(digiRootData_linkopts)  $(mcRootData_linkopts)  $(RootPolicy_linkopts)  $(GlastPolicy_linkopts)  $(ROOT_linkopts)  $(ExternalLibs_linkopts) 
runMuonCalibChain_use_linkopts=  $(calibGenCAL_linkopts)  $(reconRootData_linkopts)  $(digiRootData_linkopts)  $(mcRootData_linkopts)  $(RootPolicy_linkopts)  $(GlastPolicy_linkopts)  $(ROOT_linkopts)  $(ExternalLibs_linkopts) 
getMuSlopesXML_use_linkopts=  $(calibGenCAL_linkopts)  $(reconRootData_linkopts)  $(digiRootData_linkopts)  $(mcRootData_linkopts)  $(RootPolicy_linkopts)  $(GlastPolicy_linkopts)  $(ROOT_linkopts)  $(ExternalLibs_linkopts) 
getPedestalsXML_use_linkopts=  $(calibGenCAL_linkopts)  $(reconRootData_linkopts)  $(digiRootData_linkopts)  $(mcRootData_linkopts)  $(RootPolicy_linkopts)  $(GlastPolicy_linkopts)  $(ROOT_linkopts)  $(ExternalLibs_linkopts) 
getGainsXML_use_linkopts=  $(calibGenCAL_linkopts)  $(reconRootData_linkopts)  $(digiRootData_linkopts)  $(mcRootData_linkopts)  $(RootPolicy_linkopts)  $(GlastPolicy_linkopts)  $(ROOT_linkopts)  $(ExternalLibs_linkopts) 
genNtuple_use_linkopts=  $(calibGenCAL_linkopts)  $(reconRootData_linkopts)  $(digiRootData_linkopts)  $(mcRootData_linkopts)  $(RootPolicy_linkopts)  $(GlastPolicy_linkopts)  $(ROOT_linkopts)  $(ExternalLibs_linkopts) 
compare_constants_use_linkopts=  $(calibGenCAL_linkopts)  $(reconRootData_linkopts)  $(digiRootData_linkopts)  $(mcRootData_linkopts)  $(RootPolicy_linkopts)  $(GlastPolicy_linkopts)  $(ROOT_linkopts)  $(ExternalLibs_linkopts) 
constituents= runMuonCalib runMuonCalibChain getMuSlopesXML getPedestalsXML getGainsXML genNtuple compare_constants 
all_constituents= $(constituents)
constituentsclean= compare_constantsclean genNtupleclean getGainsXMLclean getPedestalsXMLclean getMuSlopesXMLclean runMuonCalibChainclean runMuonCalibclean 
all_constituentsclean= $(constituentsclean)
